//
//  HomeInteractor.swift
//  ttb-Interview
//
//  Created by "" on 13/2/2568 BE.
//  Copyright (c) 2568 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic {
    func processInput(input: String)
    func doSomething(request: Home.Something.Request)
}

protocol HomeDataStore {
	//var name: String { get set }
}

final class HomeInteractor: HomeBusinessLogic, HomeDataStore {
	var presenter: HomePresentationLogic?
	var worker: HomeWorker?
	//var name: String = ""
	
    func processInput(input: String) {
        // Split the input string by commas to get an array of parts
        let inputs = input.split(separator: ",")
            
        // Filter only numbers from the input by attempting to convert each part to an integer
        let inputNumbers = inputs.compactMap {
            Int($0.trimmingCharacters(in: .whitespaces)) }
        print(inputNumbers)
        
        // TODO: Handle Process Input
    }
    
    
	// MARK: Do something
	func doSomething(request: Home.Something.Request) {
		worker = HomeWorker()
		worker?.doSomeWork()
		
		let response = Home.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
